### PR TITLE
File splitter improvements- MLHR-1804, MLHR-1805, MLHR-1806, SPOI-5316

### PR DESCRIPTION
**Pull request by chandnisingh**

### CODE REVIEW

**Comment by chandnisingh** [comment]
@PramodSSImmaneni  the changes are backward compatible. The protected fields of FileSplitter are moved to AbstractFileSpitter.  The japicmp tool just shows these as removed and complains about it.

**Comment by chandnisingh** [comment]
The japicmp plugin throws following incompatibilities. All the below changes are backward compatible.

***! MODIFIED CLASS: PUBLIC com.datatorrent.lib.io.fs.FileSplitter  (not serializable)
	***! MODIFIED SUPERCLASS: com.datatorrent.lib.io.fs.AbstractFileSplitter (<- java.lang.Object)
	---! REMOVED FIELD: PROTECTED(-) long blockCount
	---! REMOVED FIELD: PUBLIC(-) FINAL(-) com.datatorrent.api.DefaultOutputPort blocksMetadataOutput
	---! REMOVED FIELD: PUBLIC(-) FINAL(-) com.datatorrent.api.DefaultOutputPort filesMetadataOutput
	---! REMOVED FIELD: PROTECTED(-) java.util.Iterator blockMetadataIterator
	---! REMOVED FIELD: PROTECTED(-) org.apache.hadoop.fs.FileSystem fs
	---! REMOVED FIELD: PROTECTED(-) FINAL(-) com.datatorrent.lib.counters.BasicCounters fileCounters
	---! REMOVED FIELD: PROTECTED(-) java.lang.Long blockSize
	---! REMOVED FIELD: PROTECTED(-) long currentWindowId
	---! REMOVED FIELD: PROTECTED(-) com.datatorrent.lib.io.fs.FileSplitter$TimeBasedDirectoryScanner scanner
	---! REMOVED FIELD: PROTECTED(-) com.datatorrent.api.Context$OperatorContext context
	---! REMOVED FIELD: PROTECTED(-) int operatorId
	---! REMOVED FIELD: PROTECTED(-) int blocksThreshold
	---! REMOVED METHOD: PUBLIC(-) com.datatorrent.lib.io.fs.FileSplitter$TimeBasedDirectoryScanner getScanner()
	---! REMOVED METHOD: PUBLIC(-) void setScanner(com.datatorrent.lib.io.fs.FileSplitter$TimeBasedDirectoryScanner)
***! MODIFIED CLASS: PUBLIC STATIC com.datatorrent.lib.io.fs.FileSplitter$TimeBasedDirectoryScanner  (not serializable)
	---! REMOVED INTERFACE: com.datatorrent.api.Component

**Comment by tweise** [comment]
The changes are not binary compatible, they require recompile of the importing code.

**Comment by amberarrow** [comment]
Even after a recompile, code using reflection like Class.getDeclaredFields()/getDeclaredMethods()
may fail since the returned values now differ but this is a low probability event.

**Comment by chandnisingh** [comment]
Can source compatible but binary incompatible change go on to next minor version update?

**Comment by tweise** [comment]
It may be difficult to refactor this in a semver compliant way. You can try to delegate methods to the base class instead removing them. And perhaps the base class can have abstract getters instead of moving the fields. But this could result in a lot of clutter. Alternatively deprecate the existing class? 

Closing this, submit to ASF repo when the issue is resolved.

**Comment by 243826** [comment]
No.

Everything has to be binary compatible. Source compatibility does not
matter with Semantic Versions.

**Pull request closed without merging**
