### PR TITLE
Replace the HashSet with ConcurrentHashSet

### PR DESCRIPTION
**Pull request by chaithu14**

### CODE REVIEW

**Comment by tweise** [comment]
Belongs to MLHR-1689

**Comment by tweise** [comment]
Please remove removePartitions and let the broker thread handle it.

**Comment by chaithu14** [comment]
Updated code as per review comments.
Cleanup the recovery directory before the test starts.

**Comment by tweise** [comment]
Shows merge conflict. Please rebase and squash.

**Pull request closed without merging**
