### PR TITLE
Spoi 4183: Proposal to change basic counters

### PR DESCRIPTION
**Pull request by chandnisingh**
- An incomplete pull request. Just created for initial review of changes to BasicCounters.
BasicCounters are strongly typed, that is, they can be only ints or longs or doubles. It cannot be a mix of number types.

Created a new Counters class which gives the following advantage
- it can be a mix of all numeric types.
- it gives flexibility to provide what aggregations can be done. This can be used for aggregating physical counters to logical counters as well as other aggregations which are needed by AppDataFramework.
- more advantages which we can discuss in the meeting

### CODE REVIEW

**Comment by ilooner** [comment]
What is the purpose of this? It looks like ints are promoted to longs and floats are promoted to doubles. How will the app data app be told what types to expect, and how will precomputed aggregations be sent to the app data app?

This may also limit support for more precise types like BigDecimal, which are necessary because float and doubles are not sufficient for dealing with things like monetary values due to roundoff error.

**Comment by chandnisingh** [comment]
Tim,
App data app needs schema as we have  discussed before and that will be send to it.
The aggregation that is done here is the physical to logical one and this is the most common implementation.

This replaces BasicCounters. Does that provide support for BigDecimal?  
As for the purpose please re- read the description of the pull request again.

**Comment by ilooner** [comment]
Will the app data app only receive logical counters? If so, currently the schema does not specify how the physical counters were aggregated to make the logical counters.

**Comment by chandnisingh** [comment]
The discussion  we had previously with David about app data still applies. App data will receive logical as well as physical

**Pull request closed without merging**
