### PR TITLE
NithinPerumal

### PR DESCRIPTION
**Pull request by NithinPerumal**
Supports providing with users with the top 10 twitter users who are tweeting as well as the top mediatypes that are being tweeted during a given period of time.  These are included in the twitter-bots project that was created.

### CODE REVIEW

**Comment by tweise** [comment]
Can one of the admins verify this patch?

**Comment by tweise** [comment]
Can one of the admins verify this patch?

**Comment by tweise** [comment]
Nithin, thanks for the submission. Can you please rebase your change to the master branch. This diff contains a lot of changes that are result of a merge and not your actual work. Please also ensure that you don't reformat files by accident.

**Comment by chandnisingh** [comment]
Closing this pull request. Nithin's changes are feature-twitterAddition branch

**Pull request closed without merging**
