### PR TITLE
MLHR 1664 AbstractFileInputOperator changes for ignoring files based on regex

### PR DESCRIPTION
**Pull request by yogidevendra**

### CODE REVIEW

**Comment by chandnisingh** [comment]
Shouldn't this be added to specific application use case and not the base operator?

**Comment by yogidevendra** [comment]
In continuation with github comments thread on 
https://github.com/DataTorrent/Malhar/pull/1270 over email.

I was in a dilemma whether it should go in the base operator or not.
Finally, I thought it would be useful for other applications which uses 
DirectoryScanner. So, better to include it in the base operator.

@Chetan
What is your opinion?

-- 
~ Yogi

**Comment by chandnisingh** [comment]
Yogi,
Directory Scanner works with a regex and the same regex could be used to ignore certain files. 
What you added is more for convenience with your use case I guess which is why I think this change should not be in Malhar.

**Comment by 243826** [comment]
Yogi,

Chandni is right: http://stackoverflow.com/questions/2078915/a-regular-expression-to-exclude-a-word-string


--
Chetan

**Comment by yogidevendra** [comment]
I was not aware of the regex to exclude a word string.

Considering word exclusion is possible using regex; I agree with Chandni that no change is required in the base operator.

Closing down this pull request.

**Pull request closed without merging**
