### PR TITLE
App data framework

### PR DESCRIPTION
**Pull request by ilooner**
This pull request is only for review do not merge

Known issues left to fix:

Add support for metadata in aggregations
There is a bug in dimensions computation producing incorrect aggregations.

### CODE REVIEW

**Comment by ilooner** [comment]
Also need to add websocket output to pi and twitter demos

**Comment by davidyan74** [comment]
Just FYI, we will need to identify the files that belong to Malhar and those to Megh and will need to create a squashed commit for each.

**Comment by tweise** [comment]
Tim, please make the websocket changes a separate request.

--
sent from mobile

**Comment by tweise** [comment]
And squash please.

--
sent from mobile

**Pull request closed without merging**
