### PR TITLE
Updating download link in README

### PR DESCRIPTION
**Pull request by sashadt**

### CODE REVIEW

**Comment by sashadt** [comment]
test this please

**Comment by sashadt** [comment]
test this now

**Comment by sashadt** [comment]
please

**Comment by sashadt** [comment]
pretty please with sugar on top?

**Comment by sashadt** [comment]
test this please

**Comment by sashadt** [comment]
Thank you Mr. Jenkins

**Comment by sashadt** [comment]
test this please

**Comment by gauravgopi123** [comment]
tested :+1:

**Pull request merged**
