### PR TITLE
SPOI-5242 dedup demo package builds

### PR DESCRIPTION
**Pull request by tweise**

### CODE REVIEW

**Comment by 243826** [comment]
Thanks for changing it Thomas. I assume that it works even though the build failed.

David, did you say it did not work on your machine when I suggested this approach yesterday?

**Comment by davidyan74** [comment]
Yes I did but I didn't try activation on an existence of a directory...

**Comment by tweise** [comment]
Unit test failures don't originate from this change. I tested it with mvn 3.2.5. David will verify it with 3.0.5.

**Comment by davidyan74** [comment]
The unit tests passed on my machine.

**Pull request merged**
