### PR TITLE
Reduced sliding window count for TwitterDemo.

### PR DESCRIPTION
**Pull request by ilooner**
Cherry pick to 3.0

### CODE REVIEW

**Comment by 243826** [comment]
Guys, there is no knowledge either in the ticket or in the pull request why something is being done. Please make sure that the tickets give the context when you are changing something that has worked well before.

**Comment by ilooner** [comment]
This is an outcome of SPOI-5738. That ticket has the explaination. I will add the explaination to the Malhar ticket

**Comment by tweise** [comment]
The ticket is SPOI-5738

**Comment by tweise** [comment]
merged to 3.0

**Pull request merged**
